package presentacion;

import javax.swing.JInternalFrame;


/**
 *
 * @author delac
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    void AbrirFrm(JInternalFrame frm){
        //FrmProductos frm = new FrmProductos();
        jdpMain.add(frm);
        frm.setVisible(true);
        frm.setLocation(
        (jdpMain.getWidth() - frm.getWidth()) / 2,
        (jdpMain.getHeight() - frm.getHeight()) / 2);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmnClientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmnCategoria = new javax.swing.JMenuItem();
        jmnLaboratorio = new javax.swing.JMenuItem();
        jmnMarcas = new javax.swing.JMenuItem();
        jmnProductos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmnVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpMainLayout = new javax.swing.GroupLayout(jdpMain);
        jdpMain.setLayout(jdpMainLayout);
        jdpMainLayout.setHorizontalGroup(
            jdpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdpMainLayout.setVerticalGroup(
            jdpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Usuarios");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes");

        jmnClientes.setText("Clientes");
        jmnClientes.addActionListener(this::jmnClientesActionPerformed);
        jMenu2.add(jmnClientes);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Mantenimiento");

        jmnCategoria.setText("Categoria");
        jmnCategoria.addActionListener(this::jmnCategoriaActionPerformed);
        jMenu4.add(jmnCategoria);

        jmnLaboratorio.setText("Laboratorio");
        jmnLaboratorio.addActionListener(this::jmnLaboratorioActionPerformed);
        jMenu4.add(jmnLaboratorio);

        jmnMarcas.setText("Marcas");
        jmnMarcas.addActionListener(this::jmnMarcasActionPerformed);
        jMenu4.add(jmnMarcas);

        jmnProductos.setText("Productos");
        jmnProductos.addActionListener(this::jmnProductosActionPerformed);
        jMenu4.add(jmnProductos);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Venta");

        jmnVenta.setText("Generar Venta");
        jmnVenta.addActionListener(this::jmnVentaActionPerformed);
        jMenu3.add(jmnVenta);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnVentaActionPerformed
        AbrirFrm(new FrmVentas(jdpMain));
    }//GEN-LAST:event_jmnVentaActionPerformed

    private void jmnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnProductosActionPerformed
        FrmProductos frm = new FrmProductos();
        AbrirFrm(frm);
        
    }//GEN-LAST:event_jmnProductosActionPerformed

    private void jmnMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnMarcasActionPerformed
        AbrirFrm(new FrmMarca());
    }//GEN-LAST:event_jmnMarcasActionPerformed

    private void jmnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnCategoriaActionPerformed
        AbrirFrm(new FrmCategoria());
    }//GEN-LAST:event_jmnCategoriaActionPerformed

    private void jmnLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnLaboratorioActionPerformed
        AbrirFrm(new FrmLaboratorio());
    }//GEN-LAST:event_jmnLaboratorioActionPerformed

    private void jmnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnClientesActionPerformed
        AbrirFrm(new FrmClientes());
    }//GEN-LAST:event_jmnClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpMain;
    private javax.swing.JMenuItem jmnCategoria;
    private javax.swing.JMenuItem jmnClientes;
    private javax.swing.JMenuItem jmnLaboratorio;
    private javax.swing.JMenuItem jmnMarcas;
    private javax.swing.JMenuItem jmnProductos;
    private javax.swing.JMenuItem jmnVenta;
    // End of variables declaration//GEN-END:variables
}
