package presentacion;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.L_Venta;
import modelo.EstadoOperacion;
import modelo.Respuesta;
import modelo.Venta;

/**
 *
 * @author delac
 */
public class FrmVentas extends javax.swing.JInternalFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVentas.class.getName());
    private JDesktopPane jdpMain;
    private L_Venta obj;
    private DefaultTableModel modelo;
    private List<Venta> lista= new ArrayList<Venta>();
    private List<Venta> listaFiltro= new ArrayList<Venta>();

    public FrmVentas(JDesktopPane pane) {
        initComponents();
        this.jdpMain= pane;
        obj = new L_Venta();
        cargarModeloTabla();
        cargarTablaProductos();
        setClosable(true);      // Permite cerrar
    setIconifiable(true);   // Minimizar
    setMaximizable(true);   // Maximizar
    setResizable(true);     // Redimensionar
    }
    
    void cargarModeloTabla(){modelo= new DefaultTableModel();
        modelo.addColumn("Venta_Id");
        modelo.addColumn("Serie");
        modelo.addColumn("Correlativo");
        modelo.addColumn("Fecha Completa");
        modelo.addColumn("Documento");
        modelo.addColumn("Cliente");
        modelo.addColumn("Total");
        modelo.addColumn("Estado");
        
        
        tblDatos.setModel(modelo);
        modelo.setRowCount(0); 
        
    }
    
    private void cargarTablaProductos() {
    Respuesta<List<Venta>> r = obj.listar();
    
    
    if (r.getEstado() == EstadoOperacion.EXITO) {
        lista = r.getDatos();
        listaFiltro=lista;
        cargarDatosModeloVenta();
    } else {
        JOptionPane.showMessageDialog(this, r.getMensaje());
    }
    }
    
    void cargarDatosModeloVenta(){
        modelo.setRowCount(0);
        
        for (Venta m : listaFiltro) {
            modelo.addRow(new Object[]{
                m.getVenta_Id(),
                m.getSerie(),
                m.getCorrelativo(),
                m.getFechaCompleta(),
                m.getTipoDocumentoVenta().getDocumentoVenta(),
                m.getCliente().getNombre(),
                m.getTotal(),
                m.getEstadoVenta().getDescripcion()                   
            });
        }
    }
    
    public void Listar(){
        cargarTablaProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Serie - correlativo", "Tipo Documento", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        FrmVentaGenerar frm = new FrmVentaGenerar(null,this);
        jdpMain.add(frm);
        frm.setLocation(
        (jdpMain.getWidth() - frm.getWidth()) / 2,
        (jdpMain.getHeight() - frm.getHeight()) / 2);
        frm.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
